export const auditCases = {
  createCampaign: "AUDIT_CREATE_CAMPAIGN",
  editCampaign: "AUDIT_EDIT_CAMPAIGN",
  createActivationCampaign: "AUDIT_CREATE_ACTIVATION_CAMPAIGN",
  editActivationCampaign: "AUDIT_EDIT_ACTIVATION_CAMPAIGN",
  requestCampaignApproval: "AUDIT_REQUEST_CAMPAIGN_APPROVAL",
  campaignApproved: "CAMPAIGN_APPROVED",
  campaignLive: "CAMPAIGN_LIVE",
  campaignBucketDeleted: "CAMPAIGN_BUCKET_DELETED",
  createReward: "AUDIT_CREATE_CAMPAIGN_REWARD",
  editReward: "AUDIT_EDIT_CAMPAIGN_REWARD",
  deleteReward: "AUDIT_DELETE_CAMPAIGN_REWARD",
  createRewardNotification: "AUDIT_CREATE_CAMPAIGN_REWARD_NOTIFICATION",
  editRewardNotification: "AUDIT_EDIT_CAMPAIGN_REWARD_NOTIFICATION",
  deleteRewardNotification: "AUDIT_DELETE_CAMPAIGN_REWARD_NOTIFICATION",
  createConditions: "AUDIT_CREATE_CAMPAIGN_CONDITION",
  createCustomKey: "AUDIT_CREATE_CUSTOM_KEY_EMAIL_LIST",
  deleteCustomKey: "AUDIT_DELETE_CUSTOM_KEY_EMAIL_LIST",
  uploadEmailList: "AUDIT_UPLOAD_EMAIL_LIST",
  createVariableSettings: "AUDIT_CREATE_VARIABLE_CAMPAIGN_SETTINGS",
  setVariableGlobalLimits: "AUDIT_SET_VARIABLE_GLOBAL_LIMITS",
  createCampaignConditions: "AUDIT_CREATE_CAMPAIGN_CONDITION",
  createVariableCampaignSettings:"AUDIT_CREATE_VARIABLE_CAMPAIGN_SETTINGS",
  createTemplateClass: "CREATE_TEMPLATE_CLASS",
  editTemplateClass: "EDIT_TEMPLATE_CLASS",
  uploadFreefundCodes: "UPLOAD_FREEFUND_CODES",
  deleteFreefundCodes: "DELETE_FREEFUND_CODES",
  uploadBulkRefund: "UPLOAD_BULK_REFUND",
  uploadBulkError : "UPLOAD_BULK_ERROR",
  createClosedUser: "CREATE_CLOSED_USER_GROUP",
  deleteClosedUser: "DELETE_CLOSED_USER_GROUP",
  deleteS3Folder: "DELETE_S3_FOLDER",
  uploadS3Folder: "UPLOAD_S3_FOLDER",
  blockBiller: "BLOCK_BILLER",
  blockBillerCircle: "BLOCK_BILLER_CIRCLE",
  baseUpload: "BASE_UPLOAD",
  createSmsNotification: "CREATE_SMS_NOTIFICATION",
  editSmsNotification: "UPDATE_SMS_NOTIFICATION",
  createBannerNotification: "CREATE_BANNER_NOTIFICATION",
  editBannerNotification: "UPDATE_BANNER_NOTIFICATION",
  createEmailNotification: "CREATE_EMAIL_NOTIFICATION",
  editEmailNotification: "UPDATE_EMAIL_NOTIFICATION",
  createIosNotification: "CREATE_IOS_NOTIFICATION",
  editIosNotification: "UPDATE_IOS_NOTIFICATION",
  createAndroidNotification: "CREATE_ANDROID_NOTIFICATION",
  editAndroidNotification: "UPDATE_ANDROID_NOTIFICATION",
  uploadFileManager: "UPLOAD_FILE_MANAGER",
  uploadOperatorsPanelBulk: "UPDATE_OPERATORS_PANEL_BULK",
  splashExclusion : "SPLASH_EXCLUSION",
  blackTileOptimisation : "BLACK_TILE_OPTIMISATION",
  uploadAMLFile: "UPLOAD_AML_FILE",
  payLaterBulkRefundUpload:"PAY_LATER_BULK_REFUND_UPLOAD",
  generateBQR:"GENERATE_BQR",
  addChatbot:"ADD_CHATBOT",
  editChatbot:"EDIT_CHATBOT",
  uploadUnsubscribedUsers : "UPLOAD_UNSUB_USER",
};
